### ISSUE TITLE
Add official version numbers and development branch

### ISSUE THREAD

**Issue by jlgreathouse** [GPUOpen-ProfessionalCompute-Tools/clARMOR#2]
Right now, all development and release happens in the main branch, and there are no official "stable" or tested releases. Changes go straight into master and those become the official version. This isn't an ideal way to release a product.

To fix this, we should add a development branch where most commits should go (and where others can submit PRs), and then we should semi-regularly catch master up to these development branch. This is akin to what clSPARSE does in its repo.

In addition, we should add a version number (tag, etc.) to each update to master so that bug reports can come back on particular versions. This also means adding a version check (--version, -v) to the clARMOR executable.

**Comment by y2kenny** [comment]
You folks should consider using git describe for versioning:
https://git-scm.com/docs/git-describe

**Comment by jlgreathouse** [comment]
I agree that we should tag (in git) our stable releases into master so that using git-describe on the master branch tells someone where they're at. Thanks for the pointer.

I'd still like to add a version-check mechanism into the application itself so that we can check versions when/if we get out-of-tree builds working. Similarly, if we get an install mechanism working (so that using the tool need not take place entirely in the source tree), we will want a version check.

**Comment by y2kenny** [comment]
oh for sure.  git-describe does not replace the need of a --version flag in the runtime binary.  In fact, the build system should call git-describe and use the returned string as the string that --version provides during runtime.  This way you can always associate a binary with the source code that generates it.

**Comment by jlgreathouse** [comment]
a708200 fixes this using the mechanism recommended by @y2kenny. Thanks!
